[package]
name = "rustyhack_server"
version = "0.1.1"
authors = ["pbellchambers <pbellchambers@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/pbellchambers/rustyhack-mmo"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyhack_lib = { path = "../rustyhack_lib" }
log = "0.4.14"
simplelog = "0.9.0"
console_engine = "1.4.2"
crossterm = { version = "0.18.2", features = ["serde"] }
legion = "0.3.1"
laminar = "0.4.0"
crossbeam-channel = "0.4.4"
serde = "1.0.123"
bincode = "1.3.1"