name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features and Improvements'
    labels:
      - 'feature'
      - 'improvement'
      - 'enhancement'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  minor:
    labels:
      - 'feature'
      - 'improvement'
      - 'enhancement'
      - 'feat'
  patch:
    labels:
      - 'bug'
      - 'fix'
      - 'bugfix'
      - 'maintenance'
      - 'chore'
exclude-labels:
  - 'skip-changelog'
template: |
  ## What’s Changed
  $CHANGES