[package]
name = "rustyhack_client"
version = "0.1.0"
authors = ["pbellchambers <pbellchambers@users.noreply.github.com>"]
edition = "2018"
repository = "https://github.com/pbellchambers/rustyhack-mmo"
license = "AGPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyhack_lib = { path = "../rustyhack_lib" }
log = "0.4.14"
simplelog = "0.9.0"
console_engine = "1.4.2"
laminar = "0.4.0"